services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: librechat-comergent:latest
    container_name: LibreChat-API
    ports:
      - 3080:3080
    depends_on:
      - mongodb
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - PROXY=${PROXY:-}
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - NO_PROXY=${NO_PROXY:-localhost,127.0.0.1,::1},${no_proxy:-},mongodb,chat-mongodb,meilisearch,chat-meilisearch,host.docker.internal
      - http_proxy=${http_proxy:-}
      - https_proxy=${https_proxy:-}
      - no_proxy=${no_proxy:-localhost,127.0.0.1,::1},${NO_PROXY:-},mongodb,chat-mongodb,meilisearch,chat-meilisearch,host.docker.internal
      - ADMIN_PANEL_URL=${ADMIN_PANEL_URL:-http://admin.localhost}
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - /home/ubuntu/LibreChat/images:/app/client/public/images
      - /home/ubuntu/LibreChat/uploads:/app/uploads
      - /home/ubuntu/LibreChat/logs:/app/api/logs
      - /home/ubuntu/LibreChat/skill:/app/skill

  admin-panel:
    image: registry.librechat.ai/clickhouse/librechat-admin-panel:latest
    container_name: admin-panel
    depends_on:
      - api
    restart: always
    environment:
      - PORT=3000
      - SESSION_SECRET=${ADMIN_PANEL_SESSION_SECRET}
      - API_SERVER_URL=http://api:3080
      - VITE_API_BASE_URL=${DOMAIN_CLIENT:-http://localhost}
      - SESSION_COOKIE_SECURE=${ADMIN_PANEL_SESSION_COOKIE_SECURE:-false}

  mongodb:
    container_name: chat-mongodb
    image: mongo:8.0.20
    restart: always
    volumes:
      - /home/ubuntu/LibreChat/data-node:/data/db
    command: mongod --noauth

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.35.1
    restart: always
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - /home/ubuntu/LibreChat/meili_data_v1.35.1:/meili_data
