services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - type: bind
        source: ./client/dist
        target: /app/client/dist
